crw_platform_homepage:
    path:     /
    defaults: { _controller: CRWPlatformBundle:Default:index }

crw_platform_contact:
    resource: "@CRWPlatformBundle/Resources/config/routing_contact.yml"
    prefix: /contact

crw_platform_annonce: 
    path:     /annonce
    defaults: { _controller: CRWPlatformBundle:Annonce:index }

crw_platform_faq: 
    path:     /FAQ 
    defaults: { _controller: CRWPlatformBundle:Faq:index }

crw_platform_legal: 
    path:     /mentions-legales 
    defaults: { _controller: CRWPlatformBundle:Legal:index }

crw_platform_cgv: 
    path:     /CGV
    defaults: { _controller: CRWPlatformBundle:Cgv:index }

crw_platform_cgu: 
    path:     /CGU
    defaults: { _controller: CRWPlatformBundle:Cgu:index }

#crw_platform_login: 
#    path:     /login
#    defaults: { _controller: CRWPlatformBundle:Login:index }