crw_platform_homepage:
    path:     /
    defaults: { _controller: CRWPlatformBundle:Default:index }

crw_platform_contact:
    resource: "@CRWPlatformBundle/Resources/config/routing_contact.yml"
    prefix: /contact

crw_platform_faq: 
    path:     /FAQ 
    defaults: { _controller: CRWPlatformBundle:Faq:index }

crw_platform_about: 
    path:     /apropos 
    defaults: { _controller: CRWPlatformBundle:About:index }

crw_platform_legal: 
    path:     /mentions-legales 
    defaults: { _controller: CRWPlatformBundle:Legal:index }

crw_platform_cgv: 
    path:     /CGV
    defaults: { _controller: CRWPlatformBundle:Cgv:index }