services:
    crw_platform.services.cookies_banner:
        class: CRW\PlatformBundle\Services\CookiesBanner
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -10 }
        arguments: ["@templating"]
